### PR TITLE
Fix Display Output on Disassembler

### LINKED ISSUE #26: Instruction prints only first 3 letters of an Instruction
Output is

AUI (...)(...)
instead of
AUIPC (...)(...)

### PR DESCRIPTION
**Pull request by jcardoso13**
Fixed  2 things

1-aligned 32-bit instructions
2-Output of AssemblyCode was with only 3 characters

Closes #26

### CODE REVIEW

File: src/riscv/decoder.rs [hunk 1]
```diff
@@ -307,23 +307,23 @@ impl Display for Instruction {
         match self.instr.instr_type {
             RVT::R => write!(
                 f,
-                "{:<8.3}{},{},{}",
+                "{:<8.6}{},{},{}",
```
Comment (jcardoso13) [inline src/riscv/decoder.rs]: Some instructions of RISCV (even if not implemented in RV32I) have a name with up to 6 chars. To improve reusability of the code, changing to 6 right off the bat stops future bugs if we were to add other features to the Adept Project

File: src/bin/disassembler.rs [hunk 2]
```diff
@@ -45,10 +45,10 @@ fn main() {
                 let decoded = Instruction::new(instruction);
 
                 if show_counter || show_all {
-                    print!("{:>8}", address);
+                    print!("{:>8} ", address);
                 }
                 if show_hex || show_all {
-                    print!("{:>8}", instruction);
+                    print!("{:>10} ", instruction);
```
Comment (jcardoso13) [inline src/bin/disassembler.rs]: To align the Output
